export const PROJECT_NUMBERS = {
  HELP_WANTED: 27,
  COMMUNITY: 29,
  CANDIDATE: 80,
  HALL_OF_FAME: 30,
  UTRECHT: 36,
  AMSTERDAM: 48,
  RVO: 49,
  LOGIUS: 53,
  DEN_HAAG: 55,
  RIJKSHUISSTIJL_COMMUNITY: 69,
};

export const PROJECTS = {
  [PROJECT_NUMBERS.HELP_WANTED]: 'HELP_WANTED',
  [PROJECT_NUMBERS.COMMUNITY]: 'COMMUNITY',
  [PROJECT_NUMBERS.CANDIDATE]: 'CANDIDATE',
  [PROJECT_NUMBERS.HALL_OF_FAME]: 'HALL_OF_FAME',
  [PROJECT_NUMBERS.UTRECHT]: 'UTRECHT',
  [PROJECT_NUMBERS.AMSTERDAM]: 'AMSTERDAM',
  [PROJECT_NUMBERS.RVO]: 'RVO',
  [PROJECT_NUMBERS.LOGIUS]: 'LOGIUS',
  [PROJECT_NUMBERS.DEN_HAAG]: 'DEN_HAAG',
  [PROJECT_NUMBERS.RIJKSHUISSTIJL_COMMUNITY]: 'RIJKSHUISSTIJL_COMMUNITY',
};
