name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm package manager
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Set up Node.js version
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: Check for known security issues with npm packages
        run: |
          echo "Auditing npm dependencies before installing them. For more information, see: https://nldesignsystem.nl/pnpm-audit"
          pnpm audit --audit-level critical

      - name: Install dependencies specified in package.json
        run: |
          pnpm install --frozen-lockfile
          pnpm ls --recursive

      - name: Run the lint script in package.json scripts
        run: |
          pnpm run --if-present lint

      - name: Run the build script in package.json scripts
        env:
          GH_ISSUES_TOKEN: ${{ secrets.GH_ISSUES_TOKEN }}
        run: |
          pnpm run --if-present build

      - name: Run the test script in package.json scripts
        run: |
          pnpm run --if-present test
